### ISSUE TITLE
audio example cuda error

### ISSUE THREAD

**Issue by bhaskar2443053** [asyml/forte#710]
**Describe the bug**
when the example is run in GPU environment. it throws this cuda error.
**To Reproduce**
python speaker_segmentation_pipeline.py
WARNING:root:Re-declared a new class named [ConstituentNode], which is probably used in import.
Traceback (most recent call last):
  File "/l/users/bhaskar.rao/work/projects/forte/examples/audio/speaker_segmentation_pipeline.py", line 115, in <module>
    pipeline.initialize()
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/forte/pipeline.py", line 680, in initialize
    self.initialize_components()
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/forte/pipeline.py", line 724, in initialize_components
    component.initialize(self.resource, config)
  File "/l/users/bhaskar.rao/work/projects/forte/examples/audio/speaker_segmentation_pipeline.py", line 44, in initialize
    self._model = pyannote.audio.Pipeline.from_pretrained(
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/pyannote/audio/core/pipeline.py", line 98, in from_pretrained
    pipeline = Klass(**config["pipeline"].get("params", {}))
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/pyannote/audio/pipelines/segmentation.py", line 92, in __init__
    model.to(device)
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 111, in to
    return super().to(*args, **kwargs)
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 189, in _apply
    self.flatten_parameters()
  File "/l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 175, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Expected behavior**

**Screenshots**
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/17160282/160807540-dbfbaa2b-5de9-4982-b3b1-96effd85c6e1.png">

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by bhaskar2443053** [comment]
yes. this was issue with the cuda version on a100 gpus.

!{sys.executable} -m pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

this solved the issue of cuda. but now i see some other error.

while running the audio example in jupyter notebook.

for pack in pipeline.process_dataset(audio_path):
    for asr_link in pack.get(Link):
        audio_utter = asr_link.get_parent()
        text_utter = asr_link.get_child()
        print(f"{text_utter.speaker}: {text_utter.text}")
        sounddevice.play(audio_utter.audio, pack.sample_rate)
        sounddevice.wait()


it throws this error:

hi
SPEAKER_00: IMG CUFVERADGE CONTINUES NOW WITH OUR THER POLITICAL REPORTE MICHAEL DOUBT N
---------------------------------------------------------------------------
PortAudioError                            Traceback (most recent call last)
Input In [9], in <cell line: 1>()
      5 print('hi')
      6 print(f"{text_utter.speaker}: {text_utter.text}")
----> 7 sounddevice.play(audio_utter.audio, pack.sample_rate)
      8 sounddevice.wait()

File /l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/sounddevice.py:174, in play(data, samplerate, mapping, blocking, loop, **kwargs)
    171     ctx.write_outdata(outdata)
    172     ctx.callback_exit()
--> 174 ctx.start_stream(OutputStream, samplerate, ctx.output_channels,
    175                  ctx.output_dtype, callback, blocking,
    176                  prime_output_buffers_using_stream_callback=False,
    177                  **kwargs)

File /l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/sounddevice.py:2576, in _CallbackContext.start_stream(self, StreamClass, samplerate, channels, dtype, callback, blocking, **kwargs)
   2573 def start_stream(self, StreamClass, samplerate, channels, dtype, callback,
   2574                  blocking, **kwargs):
   2575     stop()  # Stop previous playback/recording
-> 2576     self.stream = StreamClass(samplerate=samplerate,
   2577                               channels=channels,
   2578                               dtype=dtype,
   2579                               callback=callback,
   2580                               finished_callback=self.finished_callback,
   2581                               **kwargs)
   2582     self.stream.start()
   2583     global _last_callback

File /l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/sounddevice.py:1488, in OutputStream.__init__(self, samplerate, blocksize, device, channels, dtype, latency, extra_settings, callback, finished_callback, clip_off, dither_off, never_drop_input, prime_output_buffers_using_stream_callback)
   1458 def __init__(self, samplerate=None, blocksize=None,
   1459              device=None, channels=None, dtype=None, latency=None,
   1460              extra_settings=None, callback=None, finished_callback=None,
   1461              clip_off=None, dither_off=None, never_drop_input=None,
   1462              prime_output_buffers_using_stream_callback=None):
   1463     """PortAudio output stream (using NumPy).
   1464 
   1465     This has the same methods and attributes as `Stream`, except
   (...)
   1486 
   1487     """
-> 1488     _StreamBase.__init__(self, kind='output', wrap_callback='array',
   1489                          **_remove_self(locals()))

File /l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/sounddevice.py:811, in _StreamBase.__init__(self, kind, samplerate, blocksize, device, channels, dtype, latency, extra_settings, callback, finished_callback, clip_off, dither_off, never_drop_input, prime_output_buffers_using_stream_callback, userdata, wrap_callback)
    808         samplerate = isamplerate
    809 else:
    810     parameters, self._dtype, self._samplesize, samplerate = \
--> 811         _get_stream_parameters(kind, device, channels, dtype, latency,
    812                                extra_settings, samplerate)
    813     self._device = parameters.device
    814     self._channels = parameters.channelCount

File /l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/sounddevice.py:2654, in _get_stream_parameters(kind, device, channels, dtype, latency, extra_settings, samplerate)
   2651     samplerate = default.samplerate
   2653 device = _get_device_id(device, kind, raise_on_error=True)
-> 2654 info = query_devices(device)
   2655 if channels is None:
   2656     channels = info['max_' + kind + '_channels']

File /l/users/bhaskar.rao/forte_dev/lib/python3.9/site-packages/sounddevice.py:564, in query_devices(device, kind)
    562 info = _lib.Pa_GetDeviceInfo(device)
    563 if not info:
--> 564     raise PortAudioError('Error querying device {}'.format(device))
    565 assert info.structVersion == 2
    566 name_bytes = _ffi.string(info.name)

PortAudioError: Error querying device -1

​

**Comment by hunterhector** [comment]
Most likely it is trying to play the audio but cannot find a device:

https://github.com/asyml/forte/blob/master/examples/audio/speaker_segmentation_pipeline.py#L122

One good idea is to add a flag to the script and play the sound only when enabled.

**Comment by bhaskar2443053** [comment]
got it, removed the play option. it works now.

thank you
